let shelters = [
  {
    id: 1,
    name: "Mercury Shelter",
    address: "49 main market",
    capacity: 50,
    currentOccupancy: 32,
    phone: "9876543201",
    email: "info@mercuryshelter.org",
    description: "A safe haven providing temporary accommodation and support services.",
    services: ["Food", "Shelter", "Counseling", "Job Training"],
    operatingHours: "24/7",
    manager: "Karan Johar",
    image: "/shelters/image1.jpg",
    status: "active"
  },
  {
    id: 2,
    name: "Venus Shelter",
    address: "78 Park Road",
    capacity: 30,
    currentOccupancy: 18,
    phone: "9876543202",
    email: "contact@venusshelter.org",
    description: "Specialized shelter focusing on women and children in need of safe accommodation.",
    services: ["Food", "Shelter", "Medical Care", "Legal Aid"],
    operatingHours: "24/7",
    manager: "Salman Khan",
    image: "https://source.unsplash.com/400x250/?homeless,support",
    status: "active"
  },
  {
    id: 3,
    name: "Mars Shelter",
    address: "89 River Lane",
    capacity: 40,
    currentOccupancy: 25,
    phone: "9876543203",
    email: "hello@marsshelter.org",
    description: "Providing meals and accommodation to families in transition.",
    services: ["Food", "Shelter", "Education Support"],
    operatingHours: "8 AM - 10 PM",
    manager: "Amit Sharma",
    image: "https://source.unsplash.com/400x250/?refuge,shelter",
    status: "active"
  },
  {
    id: 4,
    name: "Jupiter Home",
    address: "12 Lake View Road",
    capacity: 45,
    currentOccupancy: 38,
    phone: "9876543204",
    email: "peace@jupiterhome.org",
    description: "Dedicated to helping individuals rebuild their lives with dignity.",
    services: ["Shelter", "Job Training", "Counseling"],
    operatingHours: "24/7",
    manager: "Priya Singh",
    image: "https://source.unsplash.com/400x250/?homeless,shelter",
    status: "active"
  },
  {
    id: 5,
    name: "Satrun Shelter",
    address: "Sector 21, Noida",
    capacity: 60,
    currentOccupancy: 44,
    phone: "9876543205",
    email: "bright@saturnshelter.org",
    description: "Empowering youth through shelter and education programs.",
    services: ["Shelter", "Food", "Education", "Counseling"],
    operatingHours: "24/7",
    manager: "Ravi Kumar",
    image: "https://source.unsplash.com/400x250/?homeless,aid",
    status: "active"
  },
  {
    id: 6,
    name: "Neptune Shelter",
    address: "MG Road, Noida",
    capacity: 55,
    currentOccupancy: 29,
    phone: "9876543206",
    email: "contact@neptuneshelter.org",
    description: "Offering safe, supportive, and empowering environments for all.",
    services: ["Shelter", "Medical Support", "Rehabilitation"],
    operatingHours: "24/7",
    manager: "Neha Verma",
    image: "https://source.unsplash.com/400x250/?help,shelter",
    status: "active"
  }
];

module.exports = shelters;
